print("how can we act with empathy and positivity when we are online")
print("be the same with everyone")
print("identify:")
print("the boy, the girl, the friend")
print ("the letter, the message, the post")
print("feel:")
print("in love and doubtful, funny and innocent, bad funny")
print("hard, easy, more easy")
print("imagine:")
print("the boy dont give the letter, the girl dont send the photo of the letter, the friend dont post the letter")
print("the boy say to her personal")
print("the girl dont send the photo and she talk to the boy")
print("say:")
print("if the boy say it personal what he feel, the girl would act different and it wouldnt be cyberbulling")

