print("como te llamas?")
nombre=input()
print("hola", nombre)
print("donde vives?")
vives=input()
print("que padre")
print("que idioma hablas?")
idioma=input()
print("tienes hermanos?")
hermanos=input()
print("cuantos años tienes?")
años=input()
print("y cuando cumples?")
cumple=input()
print("tienes novi@?")
novio=input()
print("jajaja")
print("cual es tu color favorito?")
color=input()
print("cual es tu deporte favorito?")
deporte=input()
print("que te gusta hacer?")
hacer=input()