print ("cual es tu numbre ")
nombre=input()
print("tu nombre es:", nombre )
print ("en que grado vas? ")
grado=input()
print("tu grado es:", grado )
print ("en que salon?")
salon=input()
print("tu salon es:", salon )
print ("cual es ru comida fav ")
comida=input()
print("tu comida fav es:", comida )
print ("q me cuentas ")
cuento=input()
print("me cuentas:", cuento )